### ISSUE TITLE
Notification off does not work wit FF71

### ISSUE THREAD

**Issue by BobHD** [psimonyi/openslowly#5] opened 2019-12-14 22:40 UTC
Even when the notification if not set, the notification TAB is displayed (using FF 71)

**Comment by psimonyi** [comment] 2021-02-20 03:45
This is not a bug.  The option "Notify you when loading is finished" turns on *notifications* — depending on your operating system, this is usually some sort of little popup box at the side of the screen.

The progress tab is always shown no matter what.  It cannot be disabled.  The status tab is the way to cancel or pause an ongoing operation.  Imagine accidentally starting the extension on a big bookmarks folder without having the status tab: you'd have tabs keep popping in from nowhere.  I am considering experimenting with automatically closing the status tab when the operation is complete, but I'm not convinced it's all that useful.

**Closed as completed by psimonyi** 2021-02-20 03:45 UTC
